import { TemplateConfig, ReportSection } from '../types';

// Seções disponíveis para o relatório executivo
const EXECUTIVE_SECTIONS: ReportSection[] = [
  {
    id: 'executiveSummary',
    name: 'Resumo Executivo',
    description: 'Visão geral condensada das principais métricas',
    category: 'overview',
    available: true,
    required: true,
    estimatedSize: 'small'
  },
  {
    id: 'keyInsights',
    name: 'Insights Principais',
    description: 'Descobertas mais importantes em formato executivo',
    category: 'insights',
    available: true,
    required: true,
    estimatedSize: 'medium'
  },
  {
    id: 'generalStats',
    name: 'Métricas-Chave',
    description: 'Indicadores principais de performance do grupo',
    category: 'overview',
    available: true,
    estimatedSize: 'small'
  },
  {
    id: 'trendAnalysis',
    name: 'Análise de Tendências',
    description: 'Principais tendências e direcionamentos estratégicos',
    category: 'trends',
    available: true,
    estimatedSize: 'medium'
  },
  {
    id: 'participationDecline',
    name: 'Análise de Participação',
    description: 'Evolução da participação e engajamento',
    category: 'behavior',
    available: true,
    estimatedSize: 'small'
  },
  {
    id: 'anomalyDetection',
    name: 'Alertas e Anomalias',
    description: 'Identificação de padrões anômalos que requerem atenção',
    category: 'insights',
    available: true,
    estimatedSize: 'small'
  }
];

export const executiveTemplate: TemplateConfig = {
  id: 'executive',
  name: 'Relatório Executivo',
  description: 'Visão estratégica condensada com métricas-chave e insights principais para tomada de decisão.',
  icon: 'Target',
  previewSupported: true,
  estimatedTime: '1-2 minutos',
  complexity: 'basic',
  requiredData: ['daily_stats', 'member_stats'],
  formats: ['pdf', 'png'],
  sections: EXECUTIVE_SECTIONS,
  defaultOptions: {
    includeGeneralStats: true,
    includeDailyActivity: false,
    includeMemberRanking: false,
    includeHourlyActivity: false,
    includeInsights: true,
    includeActivityPatterns: false,
    includeEngagementAnalysis: false,
    includeTimeDistribution: false,
    includeWordStatistics: false,
    includeMediaAnalysis: false,
    includePeakHours: false,
    includeConsistencyAnalysis: false,
    includeMemberEvolution: false,
    includeTrendAnalysis: true,
    includeParticipationDecline: true,
    includeParticipationTrends: false,
    includeMemberGrowth: false,
    includeEngagementRates: false,
    includeBehaviorPatterns: false,
    includeActivityPeaks: false,
    includeMemberConcentration: false,
    includeLeadershipEmergence: false,
    includeInfluencerAnalysis: false,
    includeSeasonalPatterns: false,
    includeWeekdayWeekendComparison: false,
    includeTimeZoneAnalysis: false,
    includePeakActivityAnalysis: false,
    includeContentQuality: false,
    includeTopicDistribution: false,
    includeMediaPatterns: false,
    includeResponseAnalysis: false,
    includeConversationDepth: false,
    includePeriodComparison: false,
    includeBenchmarkAnalysis: false,
    includeGrowthProjections: true,
    includeAnomalyDetection: true,
    includeNetworkAnalysis: false,
    includeCommunityDetection: false,
    includeInfluenceMapping: false,
    includeMentionAnalysis: false,
    maxMembersInRanking: 10,
    colorTheme: 'purple',
    rankingDisplay: 'minimal',
    showMemberStats: false,
    showActivityTrends: true,
    showDetailedMetrics: false,
    includeCharts: true,
    includePredictions: true,
    reportStyle: 'executive',
    chartStyle: 'minimal',
    showGridLines: false,
    showDataLabels: false,
    useGradients: false,
    animatedCharts: false,
    enablePeriodComparison: false,
    comparisonPeriods: [],
    baselineCalculation: 'trend',
    insightDepth: 'basic',
    includeRecommendations: true,
    includeActionItems: true,
    includeRiskAssessment: true,
    memberDisplayMode: 'minimal',
    includeMemberInsights: false,
    showMemberActivity: false,
    showMemberComparison: false,
    includeMemberProfiles: false,
    showMemberNetworks: false,
    includeMemberJourney: false,
    includeRawData: false,
    includeMetadata: false,
    includeDataDictionary: false,
    watermark: true,
    logoInclude: true
  }
}; 
 