import { TemplateConfig, ReportSection } from '../types';

// Seções disponíveis para o relatório de membros
const MEMBERS_SECTIONS: ReportSection[] = [
  {
    id: 'generalStats',
    name: 'Estatísticas Gerais',
    description: 'Resumo das métricas principais do grupo',
    category: 'overview',
    available: true,
    required: true,
    estimatedSize: 'small'
  },
  {
    id: 'memberRanking',
    name: 'Ranking de Membros',
    description: 'Lista detalhada dos membros mais ativos',
    category: 'members',
    available: true,
    required: true,
    estimatedSize: 'large'
  },
  {
    id: 'memberEvolution',
    name: 'Evolução dos Membros',
    description: 'Histórico de atividade individual dos membros',
    category: 'members',
    available: true,
    estimatedSize: 'large'
  },
  {
    id: 'memberConcentration',
    name: 'Concentração de Atividade',
    description: 'Análise da distribuição de participação entre membros',
    category: 'members',
    available: true,
    estimatedSize: 'medium'
  },
  {
    id: 'participationTrends',
    name: 'Tendências de Participação',
    description: 'Padrões de engajamento dos membros ao longo do tempo',
    category: 'members',
    available: true,
    estimatedSize: 'medium'
  },
  {
    id: 'engagementAnalysis',
    name: 'Análise de Engajamento',
    description: 'Métricas detalhadas de envolvimento por membro',
    category: 'behavior',
    available: true,
    estimatedSize: 'medium'
  },
  {
    id: 'influencerAnalysis',
    name: 'Análise de Influenciadores',
    description: 'Identificação dos membros mais influentes',
    category: 'members',
    available: true,
    estimatedSize: 'medium'
  },
  {
    id: 'memberProfiles',
    name: 'Perfis de Membros',
    description: 'Análise detalhada do comportamento individual',
    category: 'members',
    available: true,
    premium: true,
    estimatedSize: 'large'
  }
];

export const membersTemplate: TemplateConfig = {
  id: 'members',
  name: 'Relatório de Membros',
  description: 'Foco detalhado nos membros com ranking, análises individuais e padrões de participação.',
  icon: 'Users',
  previewSupported: true,
  estimatedTime: '2-3 minutos',
  complexity: 'intermediate',
  requiredData: ['member_stats', 'daily_stats'],
  formats: ['csv', 'pdf', 'png'],
  sections: MEMBERS_SECTIONS,
  defaultOptions: {
    includeGeneralStats: true,
    includeDailyActivity: false,
    includeMemberRanking: true,
    includeHourlyActivity: false,
    includeInsights: true,
    includeActivityPatterns: false,
    includeEngagementAnalysis: true,
    includeTimeDistribution: false,
    includeWordStatistics: true,
    includeMediaAnalysis: true,
    includePeakHours: false,
    includeConsistencyAnalysis: false,
    includeMemberEvolution: true,
    includeTrendAnalysis: false,
    includeParticipationDecline: false,
    includeParticipationTrends: true,
    includeMemberGrowth: true,
    includeEngagementRates: true,
    includeBehaviorPatterns: false,
    includeActivityPeaks: false,
    includeMemberConcentration: true,
    includeLeadershipEmergence: false,
    includeInfluencerAnalysis: true,
    includeSeasonalPatterns: false,
    includeWeekdayWeekendComparison: false,
    includeTimeZoneAnalysis: false,
    includePeakActivityAnalysis: false,
    includeContentQuality: false,
    includeTopicDistribution: false,
    includeMediaPatterns: true,
    includeResponseAnalysis: false,
    includeConversationDepth: false,
    includePeriodComparison: false,
    includeBenchmarkAnalysis: false,
    includeGrowthProjections: false,
    includeAnomalyDetection: false,
    includeNetworkAnalysis: false,
    includeCommunityDetection: false,
    includeInfluenceMapping: false,
    includeMentionAnalysis: false,
    maxMembersInRanking: 50,
    colorTheme: 'green',
    rankingDisplay: 'cards',
    showMemberStats: true,
    showActivityTrends: true,
    showDetailedMetrics: true,
    includeCharts: true,
    includePredictions: false,
    reportStyle: 'detailed',
    chartStyle: 'modern',
    showGridLines: true,
    showDataLabels: true,
    useGradients: true,
    animatedCharts: false,
    enablePeriodComparison: false,
    comparisonPeriods: [],
    baselineCalculation: 'average',
    insightDepth: 'advanced',
    includeRecommendations: true,
    includeActionItems: true,
    includeRiskAssessment: false,
    memberDisplayMode: 'comprehensive',
    includeMemberInsights: true,
    showMemberActivity: true,
    showMemberComparison: true,
    includeMemberProfiles: true,
    showMemberNetworks: false,
    includeMemberJourney: true,
    includeRawData: false,
    includeMetadata: true,
    includeDataDictionary: false,
    watermark: true,
    logoInclude: true
  }
}; 